name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up git config
      run: |
        git config --local user.email ${{ secrets.email }}
        git config --local user.name ${{ secrets.name }}

    - name: Deploy To Github Pages
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: yarn
    - run: yarn deploy


    

