name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy To Github Pages
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: yarn
    - run: yarn build
    
    - name: Init new repo in dist folder and commit generated files
      run: |
        cd dist
        git config --global init.defaultBranch
        git init
        git add -A
        git config --local --add safe.directory /github/workspace
        git config --local user.email wleklinskimateusz05@gmail.com
        git config --local user.name wleklinskimateusz
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./dist


    

